namespace Pierlam.ExpressionEval
{
    /// <summary>
    /// Base of all expression object used in a execution of an expression.
    /// The type result is important!!
    /// </summary>
    public abstract class ExpressionExecBase
    {
        // link to the expression defintion (generated by the parser)
        public ExpressionBase Expr { get; set; }
    }
}
